trigger: none

schedules:
  - cron: "0 * * * *"
    displayName: Hourly Sync
    branches:
      include:
        - master

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - checkout: self
    persistCredentials: true
  - script: |
      set -e
      git checkout master
      git pull
      git fetch -p
      git reset --hard origin/master
      git config --global pull.rebase true
      git config --global user.email "azure-pipelines@$(System.TeamProject).$(Build.Repository.Name)"
      git config --global user.name "Azure Pipelines ($(System.TeamProject) $(Build.Repository.Name))"
      git remote add upstream https://github.com/XenitAB/azure-devops-templates
      git pull upstream master
      git push origin master
      git fetch upstream --tags --prune
      git push origin --tags
      git push origin --all --prune
