parameters:
  - name: poolNameTemplate
    type: string
    default: ""
  - name: poolVmImage
    type: string
    default: "ubuntu-18.04"
  - name: sourceBranch
    type: string
    default: "refs/heads/master"
  - name: environments
    type: object
    default:
      - name: dev
      - name: qa
      - name: prod
  - name: azureSubscriptionTemplate
    type: string
  - name: terraformFolder
    type: string
  - name: validateEnabled
    type: boolean
    default: true
  - name: awsRegion
    type: string
    default: ""
  - name: awsServiceConnectionTemplate
    type: string
    default: ""

stages:
  - stage: plan
    jobs:
      - ${{ each env in parameters.environments }}:
          - job: ${{ env.name }}
            pool:
              ${{ if not(eq(parameters.poolNameTemplate, '')) }}:
                name: ${{ format(parameters.poolNameTemplate, env.name) }}
              ${{ if not(eq(parameters.poolVmImage, '')) }}:
                vmImage: ${{ parameters.poolVmImage }}
            steps:
              - ${{ if not(eq(parameters.awsRegion, '')) }}:
                  - template: ../aws_creds.yaml
                    parameters:
                      awsRegion: ${{ parameters.awsRegion }}
                      awsServiceConnection: ${{ format(parameters.awsServiceConnectionTemplate, env.name) }}

              - task: AzureCLI@1
                inputs:
                  azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env.name) }}
                  addSpnToEnvironment: true
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -e

                    if [ -n "${OPA_BLAST_RADIUS}" ] && [ "${OPA_BLAST_RADIUS}" -eq "${OPA_BLAST_RADIUS}" ] 2>/dev/null; then
                      echo OPA_BLAST_RADIUS: ${OPA_BLAST_RADIUS}
                    else
                      export OPA_BLAST_RADIUS=50
                      echo OPA_BLAST_RADIUS: ${OPA_BLAST_RADIUS}
                    fi

                    make prepare

                    if [[ "${VALIDATE_ENABLED}" == "True" ]]; then
                      make validate
                      if [[ $(git status --porcelain) ]]; then
                        git diff
                        echo 'run make validate and commit changes' 1>&2
                        exit 1
                      fi
                    fi

                    make plan
                env:
                  CI: "true"
                  DIR: ${{ parameters.terraformFolder }}
                  ENV: ${{ env.name }}
                  OPA_BLAST_RADIUS: $(opaBlastRadius)
                  VALIDATE_ENABLED: ${{ parameters.validateEnabled }}
                  CI_AWS_ACCESS_KEY_ID: $(CIAwsAccessKeyId)
                  CI_AWS_SECRET_ACCESS_KEY: $(CIAwsSecretAccessKey)
                  CI_AWS_DEFAULT_REGION: $(CIAwsDefaultRegion)
                displayName: "Terraform Plan"

              - task: PublishPipelineArtifact@0
                inputs:
                  targetPath: $(Build.Repository.LocalPath)/${{ parameters.terraformFolder }}/.terraform/plans
                  artifactName: "${{ env.name }}.enc"
                displayName: "Publish artifact"
