parameters:
  - name: poolVmImage
    type: string
    default: "ubuntu-22.04"
  - name: poolName
    type: string
    default: ""
  - name: gitopsPromotionTag
    type: string
    default: "v1.3.1"

stages:
  - stage: promote
    jobs:
      - job: Promote
        pool:
          ${{ if not(eq(parameters.poolName, '')) }}:
            name: ${{ parameters.poolName }}
          ${{ if not(eq(parameters.poolVmImage, '')) }}:
            vmImage: ${{ parameters.poolVmImage }}
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
            displayName: Get sources
          - bash: |
              git config --unset-all extensions.worktreeconfig
              git config --global user.email "azure-pipelines@${PROJECT_NAME}.${REPO_NAME}"
              git config --global user.name "Azure Pipelines (${PROJECT_NAME} ${REPO_NAME})"
              docker run -v $(pwd):/workspace ghcr.io/xenitab/gitops-promotion:${GITOPS_PROMOTION_TAG} promote --token ${TOKEN}
            env:
              GITOPS_PROMOTION_TAG: ${{ parameters.gitopsPromotionTag }}
              PROJECT_NAME: $(System.TeamProject)
              REPO_NAME: $(Build.Repository.Name)
              TOKEN: $(System.AccessToken)
            displayName: GitOps Promotion
